name: Android CI(Scene5)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r23b
        add-to-path: false

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: SSL
      # run: ./gradlew build
      run: sudo apt install openssl

    - name: 权限
      # run: ./gradlew build
      run: chmod 777 gradlew
    - name: Build with Gradle
      # run: ./gradlew build
      run: ./gradlew assembleRelease

    - name: 上传
      # run: ./gradlew build
      run: curl -T ${{ github.workspace }}/app/build/outputs/apk/release/*.apk http://ik.gengye.top:5212/dav/玩机百宝箱Beta.apk --user 123456789@qq.com:ag6R6UI9cRuVPAK2rnqwUnmarlIYhD4M
